<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0-preview.7.25380.108">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Data\Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="bin\Debug\net9.0\Business.deps.json" />
      <Content Include="bin\Debug\net9.0\Business.dll" />
      <Content Include="bin\Debug\net9.0\Business.pdb" />
      <Content Include="bin\Debug\net9.0\Data.dll" />
      <Content Include="bin\Debug\net9.0\Data.pdb" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="bin\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="bin\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="bin\**" />
    </ItemGroup>

</Project>
